# Generated by Django 2.2.3 on 2019-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
