# Generated by Django 2.2.2 on 2019-07-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190720_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='middle_nam',
            new_name='middle_name',
        ),
    ]
