# Generated by Django 2.2.3 on 2019-07-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField()),
                ('course_credits', models.IntegerField(default='10')),
                ('course_departments', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_names', to='department.Department')),
                ('subjects', models.ManyToManyField(to='courses.Subjects')),
            ],
        ),
    ]
