# Generated by Django 2.2.3 on 2019-07-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjects',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_course', to='courses.Courses'),
        ),
    ]
