# Generated by Django 2.2.2 on 2019-07-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190721_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_credits',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_departments',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.TextField(default='Computer Science'),
        ),
    ]
