# Generated by Django 2.2.2 on 2019-07-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190721_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_departments',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Department'),
        ),
    ]
