# Generated by Django 2.2.2 on 2019-07-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190721_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Department'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.TextField(),
        ),
    ]
