# Generated by Django 2.2.2 on 2019-07-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190721_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='department_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_departments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='courses.Department'),
        ),
    ]
