# Generated by Django 2.2.2 on 2019-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190721_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='subjects',
            field=models.ManyToManyField(to='courses.Subjects'),
        ),
    ]
