# Generated by Django 2.2.2 on 2019-07-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_courses_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_departments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_names', to='department.Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
