# Generated by Django 2.2.3 on 2019-07-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_courses_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='subjects',
        ),
        migrations.AddField(
            model_name='courses',
            name='subject_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_name', to='courses.Subjects'),
        ),
    ]
