# Generated by Django 2.2.3 on 2019-07-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190722_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_dept_name', to='courses.Subjects'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.TextField(),
        ),
    ]
