# Generated by Django 2.2.3 on 2019-07-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190722_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_departments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dept_names', to='courses.Department'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='courses.Department'),
        ),
    ]
