# Generated by Django 2.2.3 on 2019-07-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190722_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_departments',
            new_name='department',
        ),
    ]
