# Generated by Django 2.2.3 on 2019-07-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_department_dept_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_subject_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dept_subject_name', to='courses.Subjects'),
        ),
    ]
